name: interval_datetime_picker
description: A customizable Flutter date-time picker with interval support.
version: 0.0.2
homepage: https://github.com/aselak30/interval_datetime_picker
repository: https://github.com/aselak30/interval_datetime_picker
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
