name: interval_datetime_picker
description: A customizable Flutter date-time picker with interval support.
version: 0.0.3
homepage: https://github.com/aselak30/custom_datetime_picker
repository: https://github.com/aselak30/custom_datetime_picker
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
